spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8082
        port: 8719
security:
  oauth2:
    client:
      client-id: priceService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth.imooc.com:9090/oauth/token_key


sentinel:
  zookeeper:
    address: 127.0.0.1:2181
    path: /sentinel_rule_config
