server.port: 8080
spring:
  application:
    name: ch18-3-gateway
  cloud:
    gateway:
      routes:
      - id: service1_v1
        uri: http://localhost:8001/v1
        predicates:
        - Path=/test
        - Weight=service1, 95
      - id: service1_v2
        uri: http://localhost:8001/v2
        predicates:
        - Path=/test
        - Weight=service1, 5
      - id: service1_v3
        uri: http://localhost:8001/v2
        predicates:
        - Path=/retry/**
        filters:
          - name: Retry
            args:
              retries: 15
              series:
                - SERVER_ERROR
                - CLIENT_ERROR
              methods:
                - GET
                - POST
              exceptions:
                - java.io.IOException
                - java.util.concurrent.TimeoutException
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG